In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../01_Dataset/01_raw/Heart_raw_uncleaned.csv")
df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No

**FINDING THE ROWS AND COLUMNS**

In [ ]:
df.shape

(4520, 18)

In [4]:
df.columns

Index(['HeartDisease', 'BMI', 'Smoking', 'AlcoholDrinking', 'Stroke',
       'PhysicalHealth', 'MentalHealth', 'DiffWalking', 'Sex', 'AgeCategory',
       'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth', 'SleepTime',
       'Asthma', 'KidneyDisease', 'SkinCancer'],
      dtype='str')

**finding the data types**

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4520 entries, 0 to 4519
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   HeartDisease      4520 non-null   str
 1   BMI               4429 non-null   float64
 2   Smoking           4453 non-null   str
 3   AlcoholDrinking   4520 non-null   str
 4   Stroke            4520 non-null   str
 5   PhysicalHealth    4453 non-null   float64
 6   MentalHealth      4520 non-null   int64
 7   DiffWalking       4520 non-null   str
 8   Sex               4520 non-null   str
 9   AgeCategory       4520 non-null   str
 10  Race              4520 non-null   str
 11  Diabetic          4520 non-null   str
 12  PhysicalActivity  4520 non-null   str
 13  GenHealth         4474 non-null   str
 14  SleepTime         4475 non-null   float64
 15  Asthma            4520 non-null   str
 16  KidneyDisease     4520 non-null   str
 17  SkinCancer        4520 non-null   str
dtypes: float64(3), int64(1), str(14)
memory usage: 635.8 KB

**FINDING THE MISSING VALUES**

In [6]:
df.isnull().sum()

HeartDisease         0
BMI                 91
Smoking             67
AlcoholDrinking      0
Stroke               0
PhysicalHealth      67
MentalHealth         0
DiffWalking          0
Sex                  0
AgeCategory          0
Race                 0
Diabetic             0
PhysicalActivity     0
GenHealth           46
SleepTime           45
Asthma               0
KidneyDisease        0
SkinCancer           0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(26)

In [8]:
df.describe()

               BMI  PhysicalHealth  MentalHealth    SleepTime
count  4429.000000     4453.000000   4520.000000  4475.000000
mean     29.323775        4.122389      4.454646     7.042682
std       6.764263        8.575680      8.609997     1.597722
min       2.900000        0.000000      0.000000     1.000000
25%      24.660000        0.000000      0.000000     6.000000
50%      28.250000        0.000000      0.000000     7.000000
75%      32.980000        3.000000      5.000000     8.000000
max      80.000000       30.000000     30.000000    20.000000

In [9]:
df.nunique()

HeartDisease           2
BMI                 1161
Smoking                5
AlcoholDrinking        2
Stroke                 2
PhysicalHealth        30
MentalHealth          28
DiffWalking            2
Sex                    2
AgeCategory           13
Race                   6
Diabetic               4
PhysicalActivity       2
GenHealth              5
SleepTime             17
Asthma                 2
KidneyDisease          2
SkinCancer             2
dtype: int64

In [12]:
print("HeartDisease:")
print(df["HeartDisease"].value_counts())

print("\nSmoking:")
print(df["Smoking"].value_counts())

print("\nDiabetic:")
print(df["Diabetic"].value_counts())

print("\nGenHealth:")
print(df["GenHealth"].value_counts())

print("\nAsthma:")
print(df["Asthma"].value_counts())

HeartDisease:
HeartDisease
No     4034
Yes     486
Name: count, dtype: int64

Smoking:
Smoking
No     2533
Yes    1908
YES       4
No        4
yes       4
Name: count, dtype: int64

Diabetic:
Diabetic
No                         3628
Yes                         770
No, borderline diabetes      84
Yes (during pregnancy)       38
Name: count, dtype: int64

GenHealth:
GenHealth
Very good    1417
Good         1414
Excellent     722
Fair          665
Poor          256
Name: count, dtype: int64

Asthma:
Asthma
No     3871
Yes     649
Name: count, dtype: int64

**ab FINDING THE INVALID OR INCORRECT VALUES**

In [13]:
df.describe(include="object")

C:\Users\chira\AppData\Local\Temp\ipykernel_17848\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,HeartDisease,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,Asthma,KidneyDisease,SkinCancer
count,4520,4453,4520,4520,4520,4520,4520,4520,4520,4520,4474,4520,4520,4520
unique,2,5,2,2,2,2,13,6,4,2,5,2,2,2
top,No,No,No,No,No,Female,65-69,White,No,Yes,Very good,No,No,No
freq,4034,2533,4310,4269,3645,2615,539,3188,3628,3245,1417,3871,4308,3940

In [3]:
df = df.duplicated()

In [4]:
df

0       False
1       False
2       False
3       False
4       False
        ...
4515     True
4516     True
4517     True
4518     True
4519     True
Length: 4520, dtype: bool